spring:
  datasource:
    url: jdbc:h2:mem:main
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    ROOT: ERROR
